In [1]:
from __future__ import print_function
import torch

In [2]:
# Create 5x3 matrix
x = torch.empty(5,3)
x

tensor([[1.7150e-04, 3.0652e-41, 1.7410e-04],
        [3.0652e-41, 1.7410e-04, 3.0652e-41],
        [1.7410e-04, 3.0652e-41, 1.7150e-04],
        [3.0652e-41, 1.7150e-04, 3.0652e-41],
        [1.7150e-04, 3.0652e-41, 2.4770e-05]])

In [47]:
# Create matrix with random initialize values
# Values between 0-1
x = torch.rand(5,3)
x

tensor([[0.6244, 0.2277, 0.4348],
        [0.8979, 0.5292, 0.2152],
        [0.1704, 0.2907, 0.9612],
        [0.1775, 0.4978, 0.6001],
        [0.0123, 0.7358, 0.3189]])

In [6]:
# Create matrix with zero values
x = torch.zeros(5,3, dtype=torch.int64)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
# Construct tensor directly from data
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [12]:
# Overwrite previous x (above) with matrix of ones
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [48]:
# Overwrites dtype
# Random values
# Matrix same size
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.1309, -0.2005, -0.1495],
        [ 0.0148,  0.5327,  0.3438],
        [ 0.3951, -2.4601,  0.1134],
        [-0.0042, -0.3959, -1.5248],
        [ 0.4305, -0.8861, -1.6002]])

In [49]:
# Get size
# torch.Size is tuple
print(x.size())

torch.Size([5, 3])


# Operations

## Addition

In [50]:
# Adding matrix
y = torch.rand(5,3)
y

tensor([[0.2570, 0.2049, 0.0048],
        [0.9180, 0.4589, 0.5666],
        [0.6581, 0.1635, 0.5325],
        [0.5456, 0.1701, 0.8847],
        [0.9443, 0.4091, 0.2041]])

In [51]:
print(x+y)

tensor([[ 0.1261,  0.0045, -0.1446],
        [ 0.9328,  0.9916,  0.9105],
        [ 1.0532, -2.2966,  0.6459],
        [ 0.5413, -0.2259, -0.6401],
        [ 1.3748, -0.4770, -1.3960]])


In [52]:
# Addition 2nd way
print(torch.add(x,y))

tensor([[ 0.1261,  0.0045, -0.1446],
        [ 0.9328,  0.9916,  0.9105],
        [ 1.0532, -2.2966,  0.6459],
        [ 0.5413, -0.2259, -0.6401],
        [ 1.3748, -0.4770, -1.3960]])


In [54]:
# Addition: provide output tensor as augument
result = torch.empty(5,3) # tensor must be same size as additions of tensors
torch.add(x,y, out=result)
print(result)

tensor([[ 0.1261,  0.0045, -0.1446],
        [ 0.9328,  0.9916,  0.9105],
        [ 1.0532, -2.2966,  0.6459],
        [ 0.5413, -0.2259, -0.6401],
        [ 1.3748, -0.4770, -1.3960]])


In [21]:
# add x to y
y.add_(x)
print(y)

tensor([[ 0.6183, -1.0658,  1.2523],
        [ 0.5790,  1.3310, -2.4750],
        [ 1.3688,  2.8949,  1.4571],
        [ 1.2889,  0.9244, -0.9494],
        [ 0.4999, -0.9303,  1.3719]])


In [23]:
# Print column 1
print(x)
print(x[:,1])

tensor([[ 0.0724, -1.6412,  0.6088],
        [ 0.0577,  0.7010, -3.0751],
        [ 1.1105,  1.9849,  0.9175],
        [ 0.7105,  0.1287, -1.3437],
        [-0.1131, -1.0991,  0.8635]])
tensor([-1.6412,  0.7010,  1.9849,  0.1287, -1.0991])


In [26]:
# Resize tensor with torch.view
x = torch.randn(4,4)
y = x.view(16) # one row of 16 values from x
y

tensor([-1.0380,  0.8612,  0.3663, -1.1201, -0.9282, -0.1784, -0.5630, -0.9210,
        -0.5400,  3.0207,  0.4631, -0.0550, -0.5007, -0.8368, -0.2603, -1.8995])

In [27]:
z = x.view(-1,8) # the size -1 is inferred from other dimensions
z

tensor([[-1.0380,  0.8612,  0.3663, -1.1201, -0.9282, -0.1784, -0.5630, -0.9210],
        [-0.5400,  3.0207,  0.4631, -0.0550, -0.5007, -0.8368, -0.2603, -1.8995]])

In [28]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
x = torch.randn(1)
print(x)
print(x.item()) # Only works for one element tensor

tensor([1.2565])
1.256506085395813


# Convert from Torch tensor to NumPy array

## To NumPy

In [40]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [41]:
# Convert to NumPy with torch.numpy()
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [42]:
# NumPy array changes in values 
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## From NumPy

In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensor

In [44]:
# Use GPU/CUDA when available
# CUDA: Compute Unified Device Architecture, created by Nvidia
# Uses GPU to perform parallel programming tasks

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # Creates tensor directly on GPU
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("No GPU found!")

No GPU found!


Output (if run GPU)
tensor([0.6469], device='cuda:0')
tensor([0.6469], dtype=torch.float64)

# Autograd

Allows for automatic differentiation for all operations on a Tensor.

## Tensor

In [55]:
# Set requires_grade=True to track computations
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [56]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [57]:
# y was created as a result of operation
# hence it has grad_fn
print(y.grad_fn)

In [60]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [67]:
# .requires_grad_( ... ) changes the requires_grad attribute
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True) # requires _ after requires_grad to make a change
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradient

In [71]:
# Use .backward() to compute derivatives
print(out)
out.backward()

tensor(27., grad_fn=<MeanBackward0>)


In [72]:
# print d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [80]:
# Example of a vector-Jacobian product
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([  507.2839,  -675.5888, -1428.2904], grad_fn=<MulBackward0>)


In [81]:
v = torch.tensor([1.0, 0.1, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+03, 2.0480e+02, 2.0480e-01])


In [82]:
# Can stop autograd from tracking history on tensors with .requires_grad=True
print(x.requires_grad)
print((x**2).requires_grad)

# Use torch.no_grad() to stop tracking history
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [83]:
# Instead use .detach() to get new tensor with same content but does not require gradients
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
